### ISSUE TITLE
Document initialization process

### ISSUE THREAD

**Issue by jberkus** [elekto-io/elekto#26]
The way it is now:

We don't pull a copy of the repo until the first webhook push comes through.  This means that, if the webhook was just set up, users will see "Server Error" when they try to access elekto.

Better UX: 

If the user accesses elekto, and no repo files are found, invoke the pull method at that time.

Filing this to fix later.

**Comment by kalkayan** [comment]
There is already a CLI command to sync the metafiles with remote. So, if we are updating the `META_REPO` in `.env`. we should remove the existing meta folder and do `python console --sync` this will pull or clone the repository.

What I did:
1. changed the entires in `.env`
2. deleted the meta folder (we also don't need to do this if we change`META_PATH` to some other name)
3. ran `p console --sync`

Everything worked as expected. 

<img width="983" alt="Screenshot 2021-04-22 at 6 23 28 PM" src="https://user-images.githubusercontent.com/73003119/115717475-d7bfea00-a397-11eb-9ddd-8aba4c5544f5.png">


### Regarding the Better UX
I initially implemented this but changed to the command line and trusted webhook, due to the fact that both of these are authorized. I was hesitant in giving write access to public/user related routes.

Right now only the webhook route can update the meta (which is protected with GitHub webhook token) and none other route has the write access. 

I believe better documentation for setting up could have prevented the server error while setting up. 

cc @jberkus

**Comment by jberkus** [comment]
Eh, if we have a setup route that works, I'm good.  Keeping this open as a documentation bug.

**Comment by jberkus** [comment]
Done.
